name: 'BMLT WordPress Release'
description: 'GitHub action to publish latest WordPress release'
inputs:
  file:
    description: 'File path'
    required: true
  s3_key:
    description: 'The S3_KEY'
    required: true
  aws_account_id:
    description: 'AWS Account ID'
    required: true
  deployment_type:
    description: 'The Deployment Type'
    required: false
    default: 'wordpress'
outputs:
  put_data:
    description: 'The Data that was PUT'
    value: ${{ steps.publish-release.outputs.put_data }}
  status_code:
    description: 'The response status code'
    value: ${{ steps.publish-release.outputs.status_code }}
runs:
  using: 'composite'
  steps:
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install required Python packages
      shell: bash
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions/gh-ci-s3-artifact
        role-session-name: gh-actions-bmlt-release
        aws-region: us-east-1

    - name: Publish the WordPress release
      id: publish-release
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
        INPUT_S3_KEY: ${{ inputs.s3_key }}
        INPUT_DEPLOYMENT_TYPE: ${{ inputs.deployment_type }}
      run: python $GITHUB_ACTION_PATH/src/update_release.py
