name: 'BMLT WordPress Release'
description: 'GitHub action to publish latest wordpress release'
inputs:
  id:
    description: 'Release name'
    required: true
    default: ""
  file:
    description: 'File path'
    required: true
    default: ""
outputs:
  release_id:
    description: 'Release id'
    value: ${{ steps.publish-release.outputs.set_id }}
  file_sha:
    description: 'File sha256'
    value: ${{ steps.publish-release.outputs.file_sha }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash

    - name: Pass Inputs to Shell
      run: |
        echo "INPUT_ID=${{ inputs.id }}" >> $GITHUB_ENV
        echo "INPUT_FILE=${{ inputs.file }}" >> $GITHUB_ENV
        echo ${{ inputs.file }}
      shell: bash

    - name: Publish the release
      id: publish-release
      run: python $GITHUB_ACTION_PATH/src/update_release.py
      shell: bash
