name: Test Publish WP
on: [push]

jobs:
  test-publish:
    runs-on: ubuntu-latest
    name: Test Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Release to Latest WP
        id: publish_latest
        uses: ./
        with:
          id: crouton

      - name: Print the release name
        run: echo "${{ steps.publish_latest.outputs.release_id }}"
