name: Test Publish WP
on: [push]

jobs:
  deploy-test:
    runs-on: ubuntu-22.04
    env:
      BUILD_DIR: build
      DIST_DIR_S3: dist/s3
      DIST_DIR_GITHUB: dist/github
      GITHUB_RELEASE_FILENAME: bmlt-test-plugin.zip
    steps:
      - uses: actions/checkout@v3
        id: code-checkout
    - name: Prepare zip file
      run: |
        export ZIP_FILENAME=${S3_KEY}-build${GITHUB_RUN_NUMBER}-${GITHUB_SHA}.zip
        echo "ZIP_FILENAME=${ZIP_FILENAME}" >> $GITHUB_ENV
        zip -r $ZIP_FILENAME ./ -x "*.git*"
        mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
        mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
        mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME

  test-publish:
    runs-on: ubuntu-22.04
    name: Test Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Release to Latest WP
        id: publish_latest
        uses: ./
        with:
          id: crouton
          file: ${DIST_DIR_S3}/${ZIP_FILENAME}

      - name: Print the release name
        run: echo "${{ steps.publish_latest.outputs.release_id }}"

      - name: Print file sha
        run: echo "${{ steps.publish_latest.outputs.file_sha }}"
